"""empty message

Revision ID: 04300f20080c
Revises: 0e8e459d2e53
Create Date: 2022-04-14 14:02:45.561241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04300f20080c'
down_revision = '0e8e459d2e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
