"""empty message

Revision ID: 8ad2ec78d614
Revises: 04300f20080c
Create Date: 2022-04-14 14:03:59.921133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad2ec78d614'
down_revision = '04300f20080c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###
